# Generated by Django 4.2 on 2023-04-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='profession',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Профессия'),
        ),
    ]
